### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [trafficland/counter#7]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by ereichert** [comment]
That should have been removed before 1.0.0. It's not being used at all.

**Comment by ereichert** [comment]
See https://github.com/trafficland/counter/pull/8

**Comment by ereichert** [comment]
@dtolnay Out of curiosity, what made you look at this repo?

**Comment by dtolnay** [comment]
I saw it pop up in [this search](https://github.com/search?l=Rust&o=desc&q=rustc_serialize&s=indexed&type=Code&utf8=%E2%9C%93).
